name: toxic_talk
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.2.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - aws-c-auth=0.7.10=h0100c56_1
  - aws-c-cal=0.6.9=h5d48c4d_2
  - aws-c-common=0.9.10=hd590300_0
  - aws-c-compression=0.2.17=h7f92143_7
  - aws-c-event-stream=0.4.0=h0bcb0bb_0
  - aws-c-http=0.8.0=hd268abd_0
  - aws-c-io=0.13.36=hb3b01f7_3
  - aws-c-mqtt=0.10.0=hf5d392a_2
  - aws-c-s3=0.4.7=he8c168f_2
  - aws-c-sdkutils=0.1.13=h7f92143_0
  - aws-checksums=0.1.17=h7f92143_6
  - aws-crt-cpp=0.26.0=h3b5eec7_3
  - aws-sdk-cpp=1.11.210=hac0d6e5_8
  - binutils_impl_linux-64=2.40=hf600244_0
  - binutils_linux-64=2.40=hbdbef99_2
  - brotli-python=1.1.0=py312h30efb56_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.24.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - curl=8.5.0=hca28451_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.3=pyhd8ed1ab_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_2
  - gcc_linux-64=13.2.0=h112eaf3_2
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gfortran_impl_linux-64=13.2.0=h76e1118_2
  - glog=0.6.0=h6f12383_0
  - graphite2=1.3.13=h58526e2_1001
  - gxx_impl_linux-64=13.2.0=h338b0a0_2
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.2.1=h3d44ed6_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - httpx=0.26.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - ipython=8.19.0=pyh707e725_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=14.0.2=h84dd17c_2_cpu
  - libarrow-acero=14.0.2=h59595ed_2_cpu
  - libarrow-dataset=14.0.2=h59595ed_2_cpu
  - libarrow-flight=14.0.2=h120cb0d_2_cpu
  - libarrow-flight-sql=14.0.2=h61ff412_2_cpu
  - libarrow-gandiva=14.0.2=hacb8726_2_cpu
  - libarrow-substrait=14.0.2=h61ff412_2_cpu
  - libblas=3.9.0=19_linux64_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=19_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_2
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=19_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libparquet=14.0.2=h352af49_2_cpu
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.06.02=h7a70373_0
  - libsanitizer=13.2.0=h7e041cc_2
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=ha9c0a0a_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.3=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.3=py312h98912ed_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nltk=3.8.1=pyhd8ed1ab_0
  - nodejs=20.9.0=hb753e55_0
  - numpy=1.26.3=py312heda63a1_0
  - openai=1.6.1=pyhd8ed1ab_0
  - openssl=3.2.0=hd590300_1
  - orc=1.9.2=h4b38347_0
  - pandas=2.1.4=py312hfb8ada1_0
  - pango=1.50.14=ha41ecd1_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - praw=7.7.1=pyhd8ed1ab_0
  - prawcore=2.4.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=14.0.2=py312h176e3d2_2_cpu
  - pydantic=2.5.3=pyhd8ed1ab_0
  - pydantic-core=2.14.6=py312h4b3b743_1
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - r-base=4.3.1=h93585b2_6
  - rdma-core=49.0=hd3aeb46_2
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h8228510_1
  - regex=2023.12.25=py312h98912ed_0
  - requests=2.31.0=pyhd8ed1ab_0
  - s2n=1.4.1=h06160fa_0
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tk=8.6.13=h2797004_0
  - tktable=2.10=h0c5db8f_5
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - ucx=1.15.0=h75e419f_2
  - update_checker=0.18.0=pyh9f0ad1d_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - perspective==1.0.3

